import{nz}from"../core/random.js";import{Rational}from"../core/rational.js";import{context,frac,math,minus}from"../core/display.js";import{boolInput,choices,choiceInput,fieldsInput,generator,limit,makeTask,matrixInput,numberInput,rat,setInput,vectorInput}from"./helpers.js";
const T=(topic,id,title,fn)=>generator(`${topic}.${id}`,topic,title,fn);const sign=n=>`${n<0?"−":"+"} ${Math.abs(n)}`;const z=(a,b)=>`${minus(a)} ${sign(b)}i`;const poly=terms=>terms.filter(([,c])=>c).map(([p,c],i)=>`${i?c<0?" − ":" + ":c<0?"−":""}${Math.abs(c)===1&&p?"":Math.abs(c)}${p?"x":""}${p>1?`<sup>${p}</sup>`:""}`).join("")||"0";

export const basics=[
T("basics","signed","Vorzeichen",(r,d)=>{const m=limit(d),a=r.int(-m,m),b=r.int(-m,m),c=r.int(-m,m),v=a+b-c;return makeTask({topic:"basics",id:"basics.signed",title:"Vorzeichen",difficulty:d,prompt:context("Berechne.")+math(`${minus(a)} + (${minus(b)}) − (${minus(c)})`),answer:{type:"number",value:v},explanation:`${minus(a)} + (${minus(b)}) − (${minus(c)}) = <strong>${minus(v)}</strong>.`,complexity:2,signature:`${a}:${b}:${c}`})}),
T("basics","fractions","Bruchrechnung",(r,d)=>{const ds=d==="basis"||d==="locker"?[2,4,5,10]:[2,3,4,5,6,8,10],b=r.pick(ds),e=r.pick(ds),a=nz(r,-b,b),c=nz(r,-e,e),op=r.pick(["+","−","·"]),x=new Rational(a,b),y=new Rational(c,e),v=op==="+"?x.add(y):op==="−"?x.sub(y):x.mul(y);return makeTask({topic:"basics",id:"basics.fractions",title:"Bruchrechnung",difficulty:d,prompt:context("Berechne und kürze.")+math(`${frac(a,b)} ${op} ${frac(c,e)}`),answer:{type:"number",value:v.toString()},explanation:`${frac(a,b)} ${op} ${frac(c,e)} = <strong>${v}</strong>.`,complexity:4,signature:`${a}/${b}:${op}:${c}/${e}`})}),
T("basics","percent","Prozentrechnung",(r,d)=>{const p=r.pick([5,10,15,20,25,30,40,50,60,75]),base=r.int(2,limit(d)*2)*20,v=new Rational(p*base,100);return makeTask({topic:"basics",id:"basics.percent",title:"Prozentrechnung",difficulty:d,prompt:context("Wie viel sind …?")+math(`${p} % von ${base}`),answer:{type:"number",value:v.toString()},explanation:`${p}/100 · ${base} = <strong>${v}</strong>.`,complexity:2,signature:`${p}:${base}`})}),
T("basics","powers","Potenzen & Wurzeln",(r,d)=>{const mode=r.pick(["root","log","negative"]);let q,v,e,s;if(mode==="root"){const a=r.int(2,15);q=`√${a*a}`;v=a;e=`${a}²=${a*a}, daher <strong>${a}</strong>.`;s=`r:${a}`}else if(mode==="log"){const a=r.pick([2,3,5]),k=r.int(1,4);q=`log<sub>${a}</sub>(${a**k})`;v=k;e=`${a}<sup>${k}</sup>=${a**k}, daher <strong>${k}</strong>.`;s=`l:${a}:${k}`}else{const a=r.pick([2,3,4,5]),k=r.int(1,3);q=`${a}<sup>−${k}</sup>`;v=rat(1,a**k);e=`${a}<sup>−${k}</sup> = 1/${a**k} = <strong>${v}</strong>.`;s=`n:${a}:${k}`}return makeTask({topic:"basics",id:"basics.powers",title:"Potenzen & Wurzeln",difficulty:d,prompt:context("Berechne.")+math(q),answer:{type:"number",value:v},explanation:e,complexity:3,signature:s})}),
T("basics","order","Punkt vor Strich",(r,d)=>{const a=r.int(-9,9),b=nz(r,-9,9),c=r.int(2,7),group=r.bool(),v=group?(a+b)*c:a+b*c,q=group?`(${minus(a)} + ${minus(b)}) · ${c}`:`${minus(a)} + ${minus(b)} · ${c}`;return makeTask({topic:"basics",id:"basics.order",title:"Punkt vor Strich",difficulty:d,prompt:context("Berechne.")+math(q),answer:{type:"number",value:v},explanation:`Zuerst ${group?"die Klammer":"die Multiplikation"}; Ergebnis: <strong>${minus(v)}</strong>.`,complexity:3,signature:`${group}:${a}:${b}:${c}`})})];

export const algebra=[
T("algebra","linear","Lineare Gleichung",(r,d)=>{const x=r.int(-10,10),a=nz(r,-8,8),b=r.int(-10,10),c=a*x+b;return makeTask({topic:"algebra",id:"algebra.linear",title:"Lineare Gleichung",difficulty:d,prompt:context("Löse nach x.")+math(`${minus(a)}x ${sign(b)} = ${minus(c)}`),input:numberInput("x"),answer:{type:"number",value:x},explanation:`${minus(a)}x = ${minus(c-b)}, also <strong>x = ${minus(x)}</strong>.`,complexity:4,signature:`${a}:${b}:${c}`})}),
T("algebra","collect","Terme zusammenfassen",(r,d)=>{const p=nz(r,-8,8),q=r.int(-8,8),s=nz(r,-8,8),t=r.int(-8,8),a=p+s,b=q+t;return makeTask({topic:"algebra",id:"algebra.collect",title:"Terme zusammenfassen",difficulty:d,prompt:context("Schreibe als ax+b. Bestimme a und b.")+math(`${minus(p)}x ${sign(q)} ${sign(s)}x ${sign(t)}`),input:fieldsInput(["a","b"],2),answer:{type:"fields",values:{a,b}},explanation:`x-Terme: ${p}+${s}=${a}; Konstanten: ${q}+${t}=${b}.`,complexity:3,signature:`${p}:${q}:${s}:${t}`})}),
T("algebra","roots","Nullstellen",(r,d)=>{let x=r.int(-9,9),y=r.int(-9,9);if(x===y)y+=1;const b=-(x+y),c=x*y;return makeTask({topic:"algebra",id:"algebra.roots",title:"Nullstellen",difficulty:d,prompt:context("Bestimme beide Nullstellen.")+math(`x² ${sign(b)}x ${sign(c)} = 0`),input:setInput(),answer:{type:"set",values:[x,y]},explanation:`(x ${sign(-x)})(x ${sign(-y)})=0, also <strong>${minus(x)} und ${minus(y)}</strong>.`,complexity:5,signature:`${b}:${c}`})}),
T("algebra","composition","Funktionsverkettung",(r,d)=>{const a=nz(r,-5,5),b=r.int(-6,6),c=nz(r,-5,5),e=r.int(-6,6),x=r.int(-5,5),inside=c*x+e,v=a*inside+b;return makeTask({topic:"algebra",id:"algebra.composition",title:"Funktionsverkettung",difficulty:d,prompt:context(`f(x)=${minus(a)}x ${sign(b)}, g(x)=${minus(c)}x ${sign(e)}`)+math(`(f∘g)(${minus(x)}) = ?`),answer:{type:"number",value:v},explanation:`g(${minus(x)})=${minus(inside)}, danach f(${minus(inside)})=<strong>${minus(v)}</strong>.`,complexity:5,signature:`${a}:${b}:${c}:${e}:${x}`})}),
T("algebra","fraction-equation","Bruchgleichung",(r,d)=>{const den=r.pick([2,3,4,5,6]),x=r.int(-10,12),b=r.int(-6,6),right=new Rational(x,den).add(b);return makeTask({topic:"algebra",id:"algebra.fraction-equation",title:"Bruchgleichung",difficulty:d,prompt:context("Löse nach x.")+math(`${frac("x",den)} ${sign(b)} = ${right}`),input:numberInput("x"),answer:{type:"number",value:x},explanation:`Erst ${b<0?"addieren":"subtrahieren"}, dann mit ${den} multiplizieren: <strong>x=${minus(x)}</strong>.`,complexity:4,signature:`${den}:${b}:${right}`})})];

export const complex=[
T("complex","add","Komplexe Addition",(r,d)=>{const a=r.int(-9,9),b=r.int(-9,9),c=r.int(-9,9),e=r.int(-9,9);return makeTask({topic:"complex",id:"complex.add",title:"Komplexe Addition",difficulty:d,prompt:context("Gib Real- und Imaginärteil an.")+math(`(${z(a,b)}) + (${z(c,e)})`),input:fieldsInput([{key:"re",label:"Realteil"},{key:"im",label:"Imaginärteil"}],2),answer:{type:"fields",values:{re:a+c,im:b+e}},explanation:`Real: ${a}+${c}=${a+c}; imaginär: ${b}+${e}=${b+e}.`,complexity:3,signature:`${a}:${b}:${c}:${e}`})}),
T("complex","multiply","Komplexe Multiplikation",(r,d)=>{const a=nz(r,-5,5),b=nz(r,-5,5),c=nz(r,-5,5),e=nz(r,-5,5),re=a*c-b*e,im=a*e+b*c;return makeTask({topic:"complex",id:"complex.multiply",title:"Komplexe Multiplikation",difficulty:d,prompt:context("Multipliziere.")+math(`(${z(a,b)})(${z(c,e)})`),input:fieldsInput([{key:"re",label:"Realteil"},{key:"im",label:"Imaginärteil"}],2),answer:{type:"fields",values:{re,im}},explanation:`Realteil ${a}·${c}−${b}·${e}=${re}; Imaginärteil ${a}·${e}+${b}·${c}=${im}.`,complexity:5,signature:`${a}:${b}:${c}:${e}`})}),
T("complex","conjugate","Konjugierte Zahl",(r,d)=>{const a=r.int(-12,12),b=nz(r,-12,12);return makeTask({topic:"complex",id:"complex.conjugate",title:"Konjugierte Zahl",difficulty:d,prompt:context("Gib z̄ an.")+math(`z=${z(a,b)}`),input:fieldsInput([{key:"re",label:"Realteil"},{key:"im",label:"Imaginärteil"}],2),answer:{type:"fields",values:{re:a,im:-b}},explanation:`Nur das Vorzeichen des Imaginärteils wechselt: <strong>${z(a,-b)}</strong>.`,complexity:2,signature:`${a}:${b}`})}),
T("complex","modulus","Komplexer Betrag",(r,d)=>{const tr=r.pick([[3,4,5],[5,12,13],[6,8,10],[8,15,17]]),swap=r.bool(),a=(swap?tr[1]:tr[0])*(r.bool()?1:-1),b=(swap?tr[0]:tr[1])*(r.bool()?1:-1);return makeTask({topic:"complex",id:"complex.modulus",title:"Komplexer Betrag",difficulty:d,prompt:context("Berechne den Betrag.")+math(`|${z(a,b)}|`),answer:{type:"number",value:tr[2]},explanation:`√(${a}²+${b}²)=√${tr[2]**2}=<strong>${tr[2]}</strong>.`,complexity:3,signature:`${a}:${b}`})}),
T("complex","i-power","Potenzen von i",(r,d)=>{const n=r.int(1,180),cycle=["1","i","−1","−i"],v=cycle[n%4],opts=choices(r,v,cycle.filter(x=>x!==v));return makeTask({topic:"complex",id:"complex.i-power",title:"Potenzen von i",difficulty:d,prompt:context("Welche Zahl ist gleichwertig?")+math(`i<sup>${n}</sup>`),input:choiceInput(opts),answer:{type:"choice",value:v},explanation:`${n} mod 4 = ${n%4}; im Viererzyklus folgt <strong>${v}</strong>.`,complexity:3,signature:`${n}`})}),
T("complex","divide-i","Division durch i",(r,d)=>{const a=r.int(-10,10),b=nz(r,-10,10);return makeTask({topic:"complex",id:"complex.divide-i",title:"Division durch i",difficulty:d,prompt:context("Teile durch i.")+math(`(${z(a,b)})/i`),input:fieldsInput([{key:"re",label:"Realteil"},{key:"im",label:"Imaginärteil"}],2),answer:{type:"fields",values:{re:b,im:-a}},explanation:`1/i=−i, daher <strong>${z(b,-a)}</strong>.`,complexity:4,signature:`${a}:${b}`})})];

export const limits=[
T("limits","infinity","Grenzwert im Unendlichen",(r,d)=>{const a=nz(r,-9,9),b=r.int(-9,9),c=nz(r,-9,9),e=r.int(-9,9);return makeTask({topic:"limits",id:"limits.infinity",title:"Grenzwert im Unendlichen",difficulty:d,prompt:context("x → ∞").concat(math(frac(`${minus(a)}x ${sign(b)}`,`${minus(c)}x ${sign(e)}`))),answer:{type:"number",value:rat(a,c)},explanation:`Gleicher Grad: Verhältnis der führenden Koeffizienten = <strong>${rat(a,c)}</strong>.`,complexity:4,signature:`${a}:${b}:${c}:${e}`})}),
T("limits","removable","Kürzbarer Grenzwert",(r,d)=>{const a=nz(r,-9,9),c=nz(r,-9,9);return makeTask({topic:"limits",id:"limits.removable",title:"Kürzbarer Grenzwert",difficulty:d,prompt:context(`x → ${minus(a)}`).concat(math(`${minus(c)}·${frac(`x²−${a*a}`,`x${sign(-a)}`)}`)),answer:{type:"number",value:2*a*c},explanation:`x²−${a*a}=(x−${a})(x+${a}); kürzen und einsetzen ergibt <strong>${minus(2*a*c)}</strong>.`,complexity:5,signature:`${a}:${c}`})}),
T("limits","sin","Standardgrenzwert",(r,d)=>{const a=nz(r,-9,9),c=nz(r,-9,9);return makeTask({topic:"limits",id:"limits.sin",title:"Standardgrenzwert",difficulty:d,prompt:context("x → 0").concat(math(`${minus(c)}·${frac(`sin(${minus(a)}x)`,"x")}`)),answer:{type:"number",value:a*c},explanation:`sin(ax)/x = a·sin(ax)/(ax) → a. Mit ${c} ergibt das <strong>${a*c}</strong>.`,complexity:5,signature:`${a}:${c}`})}),
T("limits","root","Wurzel rationalisieren",(r,d)=>{const q=r.int(1,7),a=nz(r,-8,8),c=nz(r,-8,8),v=rat(a*c,2*q);return makeTask({topic:"limits",id:"limits.root",title:"Wurzel rationalisieren",difficulty:d,prompt:context("x → 0").concat(math(`${minus(c)}·${frac(`√(${q*q}${sign(a)}x)−${q}`,"x")}`)),answer:{type:"number",value:v},explanation:`Konjugiert erweitern: Nenner geht gegen ${2*q}; Zähler wird ${a*c}. Ergebnis <strong>${v}</strong>.`,complexity:6,signature:`${q}:${a}:${c}`})})];

export const sequences=[
T("sequences","arithmetic","Arithmetische Folge",(r,d)=>{const a=r.int(-12,12),step=nz(r,-8,8),n=r.int(3,6),vals=Array.from({length:n},(_,i)=>a+i*step),v=a+n*step;return makeTask({topic:"sequences",id:"sequences.arithmetic",title:"Arithmetische Folge",difficulty:d,prompt:context("Nächstes Glied?")+math(vals.map(minus).join(", ")+", …"),answer:{type:"number",value:v},explanation:`Jeweils ${step>=0?"+":""}${step}; nächstes Glied <strong>${minus(v)}</strong>.`,complexity:2,signature:`${a}:${step}:${n}`})}),
T("sequences","geometric","Geometrische Folge",(r,d)=>{const a=nz(r,-7,7),q=r.pick([-3,-2,2,3]),n=r.int(2,5),vals=Array.from({length:n},(_,i)=>a*q**i),v=a*q**n;return makeTask({topic:"sequences",id:"sequences.geometric",title:"Geometrische Folge",difficulty:d,prompt:context("Nächstes Glied?")+math(vals.map(minus).join(", ")+", …"),answer:{type:"number",value:v},explanation:`Jeweils ·${minus(q)}; nächstes Glied <strong>${minus(v)}</strong>.`,complexity:3,signature:`${a}:${q}:${n}`})}),
T("sequences","limit","Folgen-Grenzwert",(r,d)=>{const a=nz(r,-9,9),b=r.int(-9,9),c=nz(r,-9,9),e=r.int(-9,9);return makeTask({topic:"sequences",id:"sequences.limit",title:"Folgen-Grenzwert",difficulty:d,prompt:context("n → ∞").concat(math(`aₙ=${frac(`${a}n${sign(b)}`,`${c}n${sign(e)}`)}`)),answer:{type:"number",value:rat(a,c)},explanation:`Durch n teilen; Konstanten verschwinden. Ergebnis <strong>${rat(a,c)}</strong>.`,complexity:4,signature:`${a}:${b}:${c}:${e}`})}),
T("sequences","fixpoint","Fixpunkt",(r,d)=>{const den=r.pick([2,3,4,5]),L=r.int(-10,10),q=L*(den-1);return makeTask({topic:"sequences",id:"sequences.fixpoint",title:"Fixpunkt",difficulty:d,prompt:context("Die Folge konvergiert. Bestimme L.")+math(`aₙ₊₁=${frac(1,den)}aₙ ${sign(q)}/${den}`),input:numberInput("L"),answer:{type:"number",value:L},explanation:`L=L/${den}+${q}/${den}; daher <strong>L=${minus(L)}</strong>.`,complexity:5,signature:`${den}:${q}`})})];

export const series=[
T("series","finite","Endliche Summe",(r,d)=>{const a=r.int(-7,7),q=r.pick([-2,2,3]),n=r.int(2,5),vals=Array.from({length:n+1},(_,i)=>a*q**i),v=vals.reduce((s,x)=>s+x,0);return makeTask({topic:"series",id:"series.finite",title:"Endliche Summe",difficulty:d,prompt:context("Berechne.")+math(vals.map(minus).join(" + ").replace(/\+ −/g,"− ")),answer:{type:"number",value:v},explanation:`Die Summe ist <strong>${minus(v)}</strong>.`,complexity:3,signature:`${a}:${q}:${n}`})}),
T("series","infinite","Geometrische Reihe",(r,d)=>{const den=r.pick([2,3,4,5,6]),num=nz(r,-den+1,den-1),a=r.int(1,8),v=new Rational(a).div(new Rational(1).sub(new Rational(num,den)));return makeTask({topic:"series",id:"series.infinite",title:"Geometrische Reihe",difficulty:d,prompt:context("Berechne die unendliche Reihe.")+math(`${a}·Σ<sub>k=0</sub><sup>∞</sup>(${frac(num,den)})<sup>k</sup>`),answer:{type:"number",value:v.toString()},explanation:`S=a/(1−q)=<strong>${v}</strong>.`,complexity:5,signature:`${a}:${num}/${den}`})}),
T("series","radius","Konvergenzradius",(r,d)=>{const a=r.int(-10,10),R=r.pick([2,3,4,5,6,8,10]);return makeTask({topic:"series",id:"series.radius",title:"Konvergenzradius",difficulty:d,prompt:context("Bestimme Mittelpunkt a und Radius R.")+math(`Σ(${frac(`x${sign(-a)}`,R)})<sup>k</sup>`),input:fieldsInput([{key:"a",label:"Mittelpunkt a"},{key:"R",label:"Radius R"}],2),answer:{type:"fields",values:{a,R}},explanation:`|x−a|<${R}; also <strong>a=${minus(a)}, R=${R}</strong>.`,complexity:5,signature:`${a}:${R}`})}),
T("series","convergence","Konvergenz erkennen",(r,d)=>{const den=r.int(2,9),num=nz(r,-10,10),v=Math.abs(num)<den?"yes":"no",opts=choices(r,v,[v==="yes"?"no":"yes"],x=>x==="yes"?"Konvergiert":"Divergiert");return makeTask({topic:"series",id:"series.convergence",title:"Konvergenz erkennen",difficulty:d,prompt:context("Konvergiert die Reihe?")+math(`Σ(${frac(num,den)})<sup>k</sup>`),input:choiceInput(opts),answer:{type:"choice",value:v},explanation:`Geometrisch: |q| ${Math.abs(num)<den?"<":"≥"} 1, daher <strong>${v==="yes"?"konvergent":"divergent"}</strong>.`,complexity:3,signature:`${num}:${den}`})})];

export const derivatives=[
T("derivatives","polynomial","Polynom ableiten",(r,d)=>{const a=nz(r,-6,6),b=r.int(-8,8),c=r.int(-8,8),x=r.int(-3,3),v=2*a*x+b;return makeTask({topic:"derivatives",id:"derivatives.polynomial",title:"Polynom ableiten",difficulty:d,prompt:context(`f(x)=${poly([[2,a],[1,b],[0,c]])}`)+math(`f′(${minus(x)})=?`),answer:{type:"number",value:v},explanation:`f′(x)=${2*a}x ${sign(b)}; eingesetzt <strong>${minus(v)}</strong>.`,complexity:4,signature:`${a}:${b}:${c}:${x}`})}),
T("derivatives","chain","Kettenregel",(r,d)=>{const n=r.int(2,5),a=nz(r,-5,5),x=r.int(-2,2),inside=r.int(-3,3),b=inside-a*x,v=n*a*inside**(n-1);return makeTask({topic:"derivatives",id:"derivatives.chain",title:"Kettenregel",difficulty:d,prompt:context(`f(x)=(${minus(a)}x ${sign(b)})<sup>${n}</sup>`)+math(`f′(${minus(x)})=?`),answer:{type:"number",value:v},explanation:`f′=${n}·${a}·(${a}x${sign(b)})<sup>${n-1}</sup>; Ergebnis <strong>${minus(v)}</strong>.`,complexity:5,signature:`${n}:${a}:${b}:${x}`})}),
T("derivatives","product","Produktregel",(r,d)=>{const a=nz(r,-5,5),b=r.int(-6,6),c=nz(r,-5,5),e=r.int(-6,6),x=r.int(-3,3),v=a*(c*x+e)+c*(a*x+b);return makeTask({topic:"derivatives",id:"derivatives.product",title:"Produktregel",difficulty:d,prompt:context(`f(x)=(${a}x${sign(b)})(${c}x${sign(e)})`)+math(`f′(${x})=?`),answer:{type:"number",value:v},explanation:`f′=a(cx+d)+c(ax+b); eingesetzt <strong>${minus(v)}</strong>.`,complexity:6,signature:`${a}:${b}:${c}:${e}:${x}`})}),
T("derivatives","critical","Kritischer Punkt",(r,d)=>{const x=r.int(-10,10),a=nz(r,-5,5),b=-2*a*x,c=r.int(-9,9);return makeTask({topic:"derivatives",id:"derivatives.critical",title:"Kritischer Punkt",difficulty:d,prompt:context("Bei welchem x gilt f′(x)=0?")+math(`f(x)=${a}x² ${sign(b)}x ${sign(c)}`),input:numberInput("x"),answer:{type:"number",value:x},explanation:`f′=${2*a}x${sign(b)}=0, also <strong>x=${minus(x)}</strong>.`,complexity:4,signature:`${a}:${b}:${c}`})}),
T("derivatives","rules","Ableitungsregel",(r,d)=>{const k=r.pick([0,1,2]),items=[{q:"(x²+1)·sin(x)",v:"Produktregel"},{q:"sin(3x−1)",v:"Kettenregel"},{q:"(x+1)/(x−2)",v:"Quotientenregel"}],o=items[k],opts=choices(r,o.v,items.filter(x=>x!==o).map(x=>x.v));return makeTask({topic:"derivatives",id:"derivatives.rules",title:"Ableitungsregel",difficulty:d,prompt:context("Welche Regel zuerst?")+math(o.q),input:choiceInput(opts),answer:{type:"choice",value:o.v},explanation:`Der äußere Aufbau verlangt die <strong>${o.v}</strong>.`,complexity:2,signature:`${k}:${r.int(0,9999)}`})})];

const coeffInput=fieldsInput([0,1,2,3].map(i=>({key:`a${i}`,label:`a${i}`})),2),coeff=v=>({type:"fields",values:Object.fromEntries(v.map((x,i)=>[`a${i}`,x]))});
export const taylor=[
T("taylor","exp","Taylor von exp",(r,d)=>{const c=nz(r,-9,9),k=nz(r,-6,6),v=[c,c*k,rat(c*k*k,2),rat(c*k**3,6)];return makeTask({topic:"taylor",id:"taylor.exp",title:"Taylor von exp",difficulty:d,prompt:context("Bis Grad 3: a₀+a₁x+a₂x²+a₃x³").concat(math(`f(x)=${c}e<sup>${k}x</sup>`)),input:coeffInput,answer:coeff(v),explanation:`e<sup>kx</sup>=1+kx+k²x²/2+k³x³/6; Koeffizienten <strong>${v.join(", ")}</strong>.`,complexity:6,signature:`${c}:${k}`})}),
T("taylor","sin","Taylor von sin",(r,d)=>{const c=nz(r,-9,9),k=nz(r,-6,6),v=[0,c*k,0,rat(-c*k**3,6)];return makeTask({topic:"taylor",id:"taylor.sin",title:"Taylor von sin",difficulty:d,prompt:context("Bis Grad 3: a₀+a₁x+a₂x²+a₃x³").concat(math(`${c}sin(${k}x)`)),input:coeffInput,answer:coeff(v),explanation:`sin(t)=t−t³/6+…; Koeffizienten <strong>${v.join(", ")}</strong>.`,complexity:6,signature:`${c}:${k}`})}),
T("taylor","cos","Taylor von cos",(r,d)=>{const c=nz(r,-9,9),k=nz(r,-6,6),v=[c,0,rat(-c*k*k,2),0];return makeTask({topic:"taylor",id:"taylor.cos",title:"Taylor von cos",difficulty:d,prompt:context("Bis Grad 3: a₀+a₁x+a₂x²+a₃x³").concat(math(`${c}cos(${k}x)`)),input:coeffInput,answer:coeff(v),explanation:`cos(t)=1−t²/2+…; Koeffizienten <strong>${v.join(", ")}</strong>.`,complexity:5,signature:`${c}:${k}`})}),
T("taylor","geometric","Geometrische Taylorreihe",(r,d)=>{const c=nz(r,-9,9),k=nz(r,-5,5),v=[c,c*k,c*k*k,c*k**3];return makeTask({topic:"taylor",id:"taylor.geometric",title:"Geometrische Taylorreihe",difficulty:d,prompt:context("Bis Grad 3: a₀+a₁x+a₂x²+a₃x³").concat(math(`${c}/(1−${k}x)`)),input:coeffInput,answer:coeff(v),explanation:`1/(1−t)=1+t+t²+t³+…; Koeffizienten <strong>${v.join(", ")}</strong>.`,complexity:5,signature:`${c}:${k}`})})];

export const integrals=[
T("integrals","power","Potenzregel",(r,d)=>{const a=nz(r,-7,7),n=r.int(0,5),b=r.int(1,5),v=rat(a*b**(n+1),n+1);return makeTask({topic:"integrals",id:"integrals.power",title:"Potenzregel",difficulty:d,prompt:context("Berechne.")+math(`∫<sub>0</sub><sup>${b}</sup>${a}x<sup>${n}</sup>dx`),answer:{type:"number",value:v},explanation:`Stammfunktion ${a}/${n+1}·x<sup>${n+1}</sup>; Wert <strong>${v}</strong>.`,complexity:4,signature:`${a}:${n}:${b}`})}),
T("integrals","antiderivative","Stammfunktion",(r,d)=>{const a=nz(r,-10,10),b=r.int(-10,10);return makeTask({topic:"integrals",id:"integrals.antiderivative",title:"Stammfunktion",difficulty:d,prompt:context("F(x)=Ax²+Bx ohne Konstante. Bestimme A und B.")+math(`f(x)=${a}x ${sign(b)}`),input:fieldsInput(["A","B"],2),answer:{type:"fields",values:{A:rat(a,2),B:b}},explanation:`Integrieren ergibt <strong>A=${rat(a,2)}, B=${b}</strong>.`,complexity:3,signature:`${a}:${b}`})}),
T("integrals","partial","Partialbruchzerlegung",(r,d)=>{const c=r.int(1,9),A=nz(r,-7,7),B=nz(r,-7,7),m=A+B,n=A*c;return makeTask({topic:"integrals",id:"integrals.partial",title:"Partialbruchzerlegung",difficulty:d,prompt:context("Bestimme A und B.")+math(`${frac(`${m}x${sign(n)}`,`x(x+${c})`)}=${frac("A","x")}+${frac("B",`x+${c}`)}`),input:fieldsInput(["A","B"],2),answer:{type:"fields",values:{A,B}},explanation:`A(x+${c})+Bx=(A+B)x+${c}A; daher <strong>A=${A}, B=${B}</strong>.`,complexity:6,signature:`${c}:${m}:${n}`})}),
T("integrals","method","Integrationsmethode",(r,d)=>{const items=[{q:"∫2x·cos(x²)dx",v:"Substitution"},{q:"∫x·eˣdx",v:"Partielle Integration"},{q:"∫(2x+1)/(x²+x)dx",v:"Partialbruchzerlegung"}],o=r.pick(items),opts=choices(r,o.v,items.filter(x=>x!==o).map(x=>x.v));return makeTask({topic:"integrals",id:"integrals.method",title:"Integrationsmethode",difficulty:d,prompt:context("Bester erster Schritt?")+math(o.q),input:choiceInput(opts),answer:{type:"choice",value:o.v},explanation:`Die Struktur passt direkt zur <strong>${o.v}</strong>.`,complexity:9,signature:`${items.indexOf(o)}:${r.int(0,9999)}`})})];
