import{nz}from"../core/random.js";import{Rational}from"../core/rational.js";import{context,frac,math,matrix,minus,vector}from"../core/display.js";import{boolInput,choices,choiceInput,fieldsInput,generator,makeTask,matrixInput,numberInput,rat,setInput,vectorInput}from"./helpers.js";
const T=(topic,id,title,fn)=>generator(`${topic}.${id}`,topic,title,fn);const sign=n=>`${n<0?"−":"+"} ${Math.abs(n)}`;const eq=(a,b,c)=>`${minus(a)}x ${sign(b)}y = ${minus(c)}`;const m2=(r,n=8)=>[[r.int(-n,n),r.int(-n,n)],[r.int(-n,n),r.int(-n,n)]];

export const matrices=[
T("matrices","add","Matrixaddition",(r,d)=>{const A=m2(r),B=m2(r),V=A.map((row,i)=>row.map((x,j)=>x+B[i][j]));return makeTask({topic:"matrices",id:"matrices.add",title:"Matrixaddition",difficulty:d,prompt:context("Berechne A+B.")+math(`${matrix(A)} + ${matrix(B)}`),input:matrixInput(2,2),answer:{type:"matrix",values:V},explanation:`Eintragsweise addieren: <strong>${matrix(V)}</strong>.`,complexity:4,signature:`${A.flat()}:${B.flat()}`})}),
T("matrices","det","2×2-Determinante",(r,d)=>{const A=m2(r),v=A[0][0]*A[1][1]-A[0][1]*A[1][0];return makeTask({topic:"matrices",id:"matrices.det",title:"2×2-Determinante",difficulty:d,prompt:context("Berechne det(A).").concat(math(matrix(A))),input:numberInput("det(A)"),answer:{type:"number",value:v},explanation:`${A[0][0]}·${A[1][1]}−${A[0][1]}·${A[1][0]}=<strong>${minus(v)}</strong>.`,complexity:4,signature:A.flat().join(":")})}),
T("matrices","vector","Matrix-Vektor-Produkt",(r,d)=>{const A=m2(r,6),x=[r.int(-5,5),r.int(-5,5)],v={x:A[0][0]*x[0]+A[0][1]*x[1],y:A[1][0]*x[0]+A[1][1]*x[1]};return makeTask({topic:"matrices",id:"matrices.vector",title:"Matrix-Vektor-Produkt",difficulty:d,prompt:context("Berechne.")+math(`${matrix(A)}·${vector(x)}`),input:vectorInput(),answer:{type:"fields",values:v},explanation:`Zeilen mal Spalte ergibt <strong>${vector([v.x,v.y])}</strong>.`,complexity:5,signature:`${A.flat()}:${x}`})}),
T("matrices","triangular","Dreiecksmatrix",(r,d)=>{const diag=[nz(r,-6,6),nz(r,-6,6),nz(r,-6,6)],A=[[diag[0],r.int(-8,8),r.int(-8,8)],[0,diag[1],r.int(-8,8)],[0,0,diag[2]]],v=diag.reduce((a,b)=>a*b,1);return makeTask({topic:"matrices",id:"matrices.triangular",title:"Dreiecksmatrix",difficulty:d,prompt:context("Berechne die Determinante.").concat(math(matrix(A))),answer:{type:"number",value:v},explanation:`Produkt der Diagonale: ${diag.join("·")} = <strong>${minus(v)}</strong>.`,complexity:3,signature:A.flat().join(":")})}),
T("matrices","inverse-entry","Eintrag der Inversen",(r,d)=>{let A=[[1,0],[0,1]],det=1;for(let i=0;i<40;i++){const C=m2(r,5),q=C[0][0]*C[1][1]-C[0][1]*C[1][0];if(q){A=C;det=q;break}}const pos=r.pick([[0,0],[0,1],[1,0],[1,1]]),adj=[[A[1][1],-A[0][1]],[-A[1][0],A[0][0]]],v=rat(adj[pos[0]][pos[1]],det);return makeTask({topic:"matrices",id:"matrices.inverse-entry",title:"Eintrag der Inversen",difficulty:d,prompt:context(`Bestimme (A⁻¹)${pos[0]+1}${pos[1]+1}.`).concat(math(matrix(A))),answer:{type:"number",value:v},explanation:`A⁻¹=(1/${det})${matrix(adj)}; gesuchter Eintrag <strong>${v}</strong>.`,complexity:7,signature:`${A.flat()}:${pos}`})}),
T("matrices","invertible","Invertierbarkeit",(r,d)=>{const A=m2(r),det=A[0][0]*A[1][1]-A[0][1]*A[1][0],v=det!==0?"yes":"no",opts=choices(r,v,[v==="yes"?"no":"yes"],x=>x==="yes"?"Ja, invertierbar":"Nein");return makeTask({topic:"matrices",id:"matrices.invertible",title:"Invertierbarkeit",difficulty:d,prompt:context("Ist A invertierbar?").concat(math(matrix(A))),input:choiceInput(opts),answer:{type:"choice",value:v},explanation:`det(A)=${det}; daher <strong>${v==="yes"?"invertierbar":"nicht invertierbar"}</strong>.`,complexity:4,signature:A.flat().join(":")})})];

export const linearSystems=[
T("linearSystems","solve","2×2-System",(r,d)=>{const x=r.int(-7,7),y=r.int(-7,7);let a=1,b=0,c=0,e=1;for(let i=0;i<40;i++){const q=[nz(r,-6,6),r.int(-6,6),r.int(-6,6),nz(r,-6,6)],det=q[0]*q[3]-q[1]*q[2];if(det&&Math.abs(det)<=24){[a,b,c,e]=q;break}}const u=a*x+b*y,v=c*x+e*y;return makeTask({topic:"linearSystems",id:"linearSystems.solve",title:"2×2-System",difficulty:d,prompt:context("Löse das System.")+math(`${eq(a,b,u)}<br>${eq(c,e,v)}`),input:vectorInput(),answer:{type:"fields",values:{x,y}},explanation:`Elimination liefert <strong>x=${minus(x)}, y=${minus(y)}</strong>.`,complexity:7,signature:`${a}:${b}:${c}:${e}:${u}:${v}`})}),
T("linearSystems","type","Lösungsanzahl",(r,d)=>{const a=nz(r,-5,5),b=nz(r,-5,5),c=r.int(-8,8),k=r.pick([-3,-2,2,3]),same=r.bool(),v=same?"infinite":"none",right=k*c+(same?0:nz(r,-4,4)),labels={unique:"Eindeutig",none:"Keine Lösung",infinite:"Unendlich viele"},opts=choices(r,v,Object.keys(labels).filter(x=>x!==v),x=>labels[x]);return makeTask({topic:"linearSystems",id:"linearSystems.type",title:"Lösungsanzahl",difficulty:d,prompt:context("Wie viele Lösungen?")+math(`${eq(a,b,c)}<br>${eq(k*a,k*b,right)}`),input:choiceInput(opts),answer:{type:"choice",value:v},explanation:`Linke Seite ist das ${k}-Fache, rechte Seite ${same?"auch":"nicht"}: <strong>${labels[v]}</strong>.`,complexity:9,signature:`${a}:${b}:${c}:${k}:${right}`})}),
T("linearSystems","gauss","Gauß-Faktor",(r,d)=>{const pivot=nz(r,-6,6),m=new Rational(nz(r,-8,8),r.pick([1,1,2])),a21=m.mul(pivot);return makeTask({topic:"linearSystems",id:"linearSystems.gauss",title:"Gauß-Faktor",difficulty:d,prompt:context("Z₂←Z₂−mZ₁. Welches m eliminiert den ersten Eintrag?")+math(`a₁₁=${pivot}, a₂₁=${a21}`),input:numberInput("m"),answer:{type:"number",value:m.toString()},explanation:`m=a₂₁/a₁₁=<strong>${m}</strong>.`,complexity:4,signature:`${pivot}:${a21}:${r.int(-99,99)}`})}),
T("linearSystems","back","Rückwärtssubstitution",(r,d)=>{const x=r.int(-8,8),y=r.int(-8,8),a=nz(r,-6,6),b=r.int(-6,6),e=nz(r,-6,6),u=a*x+b*y,v=e*y;return makeTask({topic:"linearSystems",id:"linearSystems.back",title:"Rückwärtssubstitution",difficulty:d,prompt:context("Löse das Dreieckssystem.")+math(`${eq(a,b,u)}<br>${e}y=${v}`),input:vectorInput(),answer:{type:"fields",values:{x,y}},explanation:`Unten y=${y}; oben eingesetzt x=<strong>${x}</strong>.`,complexity:5,signature:`${a}:${b}:${e}:${u}:${v}`})}),
T("linearSystems","homogeneous","Homogenes System",(r,d)=>{const a=nz(r,-8,8),b=nz(r,-8,8),detNonzero=r.bool(),A=detNonzero?[[a,b],[-b,a]]:[[a,b],[2*a,2*b]],v=detNonzero?"only-zero":"nontrivial",opts=choices(r,v,[v==="only-zero"?"nontrivial":"only-zero"],x=>x==="only-zero"?"Nur die Nulllösung":"Auch nichttriviale Lösungen");return makeTask({topic:"linearSystems",id:"linearSystems.homogeneous",title:"Homogenes System",difficulty:d,prompt:context("Welche Lösungsart hat Ax=0?").concat(math(matrix(A))),input:choiceInput(opts),answer:{type:"choice",value:v},explanation:`det(A) ${detNonzero?"≠":"="} 0; daher <strong>${detNonzero?"nur die Nulllösung":"auch nichttriviale Lösungen"}</strong>.`,complexity:9,signature:A.flat().join(":")})})];

export const vectorSpaces=[
T("vectorSpaces","combination","Linearkombination",(r,d)=>{const p=r.int(-7,7),q=r.int(-7,7),a=nz(r,-5,5),b=r.int(-5,5),c=r.int(-5,5);let e=nz(r,-5,5);if(a*e-b*c===0)e+=1;const target=[p*a+q*c,p*b+q*e];return makeTask({topic:"vectorSpaces",id:"vectorSpaces.combination",title:"Linearkombination",difficulty:d,prompt:context("Bestimme p und q.")+math(`p${vector([a,b])}+q${vector([c,e])}=${vector(target)}`),input:vectorInput(["p","q"]),answer:{type:"fields",values:{p,q}},explanation:`Das kleine System ergibt <strong>p=${p}, q=${q}</strong>.`,complexity:6,signature:`${a}:${b}:${c}:${e}:${target}`})}),
T("vectorSpaces","dimension","Dimension von Pₙ",(r,d)=>{const n=r.int(1,12);return makeTask({topic:"vectorSpaces",id:"vectorSpaces.dimension",title:"Dimension von Pₙ",difficulty:d,prompt:context("Grad höchstens n.")+math(`dim(P<sub>${n}</sub>)=?`),answer:{type:"number",value:n+1},explanation:`Basis {1,x,…,x<sup>${n}</sup>}: <strong>${n+1}</strong> Elemente.`,complexity:2,signature:`${n}:${r.int(0,9999)}`})}),
T("vectorSpaces","kernel","Kern",(r,d)=>{const a=nz(r,-9,9),b=nz(r,-9,9);return makeTask({topic:"vectorSpaces",id:"vectorSpaces.kernel",title:"Kern",difficulty:d,prompt:context("Gib einen Vektor ≠0 im Kern an.")+math(`A=${matrix([[a,b]])}`),input:vectorInput(),answer:{type:"proportional",values:{x:b,y:-a}},explanation:`Zum Beispiel <strong>${vector([b,-a])}</strong>; jedes nichtnull Vielfache gilt.`,complexity:5,signature:`${a}:${b}`})}),
T("vectorSpaces","rank","Rang",(r,d)=>{const a=nz(r,-6,6),b=nz(r,-6,6),dep=r.bool(),k=r.pick([-3,-2,2,3]),row=dep?[k*a,k*b]:[-b,a],v=dep?"1":"2",opts=choices(r,v,["0","1","2"].filter(x=>x!==v));return makeTask({topic:"vectorSpaces",id:"vectorSpaces.rank",title:"Rang",difficulty:d,prompt:context("Bestimme den Rang.").concat(math(matrix([[a,b],row]))),input:choiceInput(opts),answer:{type:"choice",value:v},explanation:`Zeilen sind ${dep?"proportional":"unabhängig"}; Rang <strong>${v}</strong>.`,complexity:4,signature:`${a}:${b}:${row}`})}),
T("vectorSpaces","subspace","Untervektorraum",(r,d)=>{const a=nz(r,-7,7),b=nz(r,-7,7),c=r.bool()?0:nz(r,-8,8),v=c===0?"yes":"no",opts=choices(r,v,[v==="yes"?"no":"yes"],x=>x==="yes"?"Ja":"Nein");return makeTask({topic:"vectorSpaces",id:"vectorSpaces.subspace",title:"Untervektorraum",difficulty:d,prompt:context("Ist W⊂ℝ² ein Untervektorraum?")+math(`W={(x,y)|${a}x${sign(b)}y=${c}}`),input:choiceInput(opts),answer:{type:"choice",value:v},explanation:`Der Nullvektor ist ${c===0?"enthalten":"nicht enthalten"}: <strong>${v==="yes"?"Ja":"Nein"}</strong>.`,complexity:3,signature:`${a}:${b}:${c}`})})];

export const orthogonality=[
T("orthogonality","dot","Skalarprodukt",(r,d)=>{const u=[r.int(-9,9),r.int(-9,9)],v=[r.int(-9,9),r.int(-9,9)],x=u[0]*v[0]+u[1]*v[1];return makeTask({topic:"orthogonality",id:"orthogonality.dot",title:"Skalarprodukt",difficulty:d,prompt:context("Berechne u·v.")+math(`${vector(u)}·${vector(v)}`),answer:{type:"number",value:x},explanation:`${u[0]}·${v[0]}+${u[1]}·${v[1]}=<strong>${x}</strong>.`,complexity:3,signature:`${u}:${v}`})}),
T("orthogonality","norm","Norm",(r,d)=>{const tr=r.pick([[3,4,5],[5,12,13],[6,8,10],[8,15,17]]),u=[tr[0]*(r.bool()?1:-1),tr[1]*(r.bool()?1:-1)];return makeTask({topic:"orthogonality",id:"orthogonality.norm",title:"Norm",difficulty:d,prompt:context("Berechne die Norm.")+math(`‖${vector(u)}‖`),answer:{type:"number",value:tr[2]},explanation:`√(${u[0]}²+${u[1]}²)=<strong>${tr[2]}</strong>.`,complexity:3,signature:`${u}`})}),
T("orthogonality","projection","Projektion",(r,d)=>{const u=r.pick([[1,1],[1,-1],[2,0],[0,2]]),v=[r.int(-9,9),r.int(-9,9)],n=v[0]*u[0]+v[1]*u[1],den=u[0]**2+u[1]**2,ans={x:rat(n*u[0],den),y:rat(n*u[1],den)};return makeTask({topic:"orthogonality",id:"orthogonality.projection",title:"Projektion",difficulty:d,prompt:context("Projiziere v auf u.")+math(`v=${vector(v)}, u=${vector(u)}`),input:vectorInput(),answer:{type:"fields",values:ans},explanation:`(v·u)/(u·u)·u = <strong>${vector([ans.x,ans.y])}</strong>.`,complexity:6,signature:`${u}:${v}`})}),
T("orthogonality","normal","Normalenvektor",(r,d)=>{const u=[nz(r,-9,9),nz(r,-9,9)];return makeTask({topic:"orthogonality",id:"orthogonality.normal",title:"Normalenvektor",difficulty:d,prompt:context("Gib einen Vektor ≠0 orthogonal zu u an.")+math(`u=${vector(u)}`),input:vectorInput(),answer:{type:"proportional",values:{x:-u[1],y:u[0]}},explanation:`Zum Beispiel <strong>${vector([-u[1],u[0]])}</strong>; Vorzeichen und Vielfache sind erlaubt.`,complexity:3,signature:`${u}`})}),
T("orthogonality","least-squares","Ausgleichsgerade",(r,d)=>{const m=nz(r,-6,6),b=r.int(-8,8),e=r.int(1,4),pts=[[-1,b-m+e],[0,b-2*e],[1,b+m+e]];return makeTask({topic:"orthogonality",id:"orthogonality.least-squares",title:"Ausgleichsgerade",difficulty:d,prompt:context(`Punkte ${pts.map(p=>`(${p[0]}|${p[1]})`).join(", ")}; y=mx+b.`)+math("Bestimme m und b."),input:fieldsInput(["m","b"],2),answer:{type:"fields",values:{m,b}},explanation:`Symmetrie liefert Mittelwert b=${b} und Steigung m=${m}.`,complexity:7,signature:`${m}:${b}:${e}`})})];

export const decompositions=[
T("decompositions","lr","LR-Faktor",(r,d)=>{const p=nz(r,-6,6),l=nz(r,-5,5),A=[[p,r.int(-7,7)],[l*p,r.int(-8,8)]];return makeTask({topic:"decompositions",id:"decompositions.lr",title:"LR-Faktor",difficulty:d,prompt:context("Bestimme l₂₁.").concat(math(matrix(A))),input:numberInput("l₂₁"),answer:{type:"number",value:l},explanation:`l₂₁=a₂₁/a₁₁=<strong>${l}</strong>.`,complexity:4,signature:A.flat().join(":")})}),
T("decompositions","forward","Vorwärtssubstitution",(r,d)=>{const l=nz(r,-6,6),y1=r.int(-8,8),y2=r.int(-8,8),b=[y1,l*y1+y2];return makeTask({topic:"decompositions",id:"decompositions.forward",title:"Vorwärtssubstitution",difficulty:d,prompt:context("Löse Ly=b.")+math(`${matrix([[1,0],[l,1]])}y=${vector(b)}`),input:vectorInput(["y1","y2"]),answer:{type:"fields",values:{y1,y2}},explanation:`Oben y₁=${y1}; unten folgt <strong>y₂=${y2}</strong>.`,complexity:5,signature:`${l}:${b}`})}),
T("decompositions","orthogonal","QR-Idee",(r,d)=>{const a=nz(r,-7,7),b=nz(r,-7,7),yes=r.bool(),col=yes?[-b,a]:[b,a],v=yes?"yes":"no",opts=choices(r,v,[v==="yes"?"no":"yes"],x=>x==="yes"?"Ja, orthogonal":"Nein");return makeTask({topic:"decompositions",id:"decompositions.orthogonal",title:"QR-Idee",difficulty:d,prompt:context("Sind die Spalten orthogonal?").concat(math(matrix([[a,col[0]],[b,col[1]]]))),input:choiceInput(opts),answer:{type:"choice",value:v},explanation:`Skalarprodukt = ${a*col[0]+b*col[1]}; daher <strong>${yes?"ja":"nein"}</strong>.`,complexity:3,signature:`${a}:${b}:${col}`})}),
T("decompositions","pivot","Pivotisierung",(r,d)=>{const a=r.int(1,5),b=r.int(6,12),v="swap",opts=choices(r,v,["keep","scale"],x=>({swap:"Zeilen tauschen",keep:"Ohne Tausch fortfahren",scale:"Erste Zeile normieren"}[x]));return makeTask({topic:"decompositions",id:"decompositions.pivot",title:"Pivotisierung",difficulty:d,prompt:context("Was ist bei partieller Pivotisierung zuerst sinnvoll?")+math(matrix([[a,r.int(-9,9)],[b,r.int(-9,9)]])),input:choiceInput(opts),answer:{type:"choice",value:v},explanation:`Der betragsgrößere Pivot ${b} gehört nach oben: <strong>Zeilen tauschen</strong>.`,complexity:8,signature:`${a}:${b}:${r.int(0,9999)}`})})];

export const numericalMethods=[
T("numericalMethods","newton","Newton-Schritt",(r,d)=>{const x=nz(r,1,10),s=r.int(1,100),v=rat(x*x+s,2*x);return makeTask({topic:"numericalMethods",id:"numericalMethods.newton",title:"Newton-Schritt",difficulty:d,prompt:context(`f(x)=x²−${s}, x₀=${x}`).concat(math("Berechne x₁.")),input:numberInput("x₁"),answer:{type:"number",value:v},explanation:`x₁=x₀−f/f′=(${x*x}+${s})/${2*x}=<strong>${v}</strong>.`,complexity:6,signature:`${x}:${s}`})}),
T("numericalMethods","euler","Euler-Schritt",(r,d)=>{const t=r.int(-3,3),y=r.int(-8,8),a=r.int(-4,4),b=r.int(-4,4),hn=r.int(1,4),hd=r.pick([2,4,5,10]),s=a*t+b*y,v=new Rational(y).add(new Rational(hn,hd).mul(s));return makeTask({topic:"numericalMethods",id:"numericalMethods.euler",title:"Euler-Schritt",difficulty:d,prompt:context(`y′=${a}t${sign(b)}y; (t₀,y₀)=(${t},${y}), h=${hn}/${hd}`).concat(math("Bestimme y₁.")),input:numberInput("y₁"),answer:{type:"number",value:v.toString()},explanation:`Steigung ${s}; y₁=y₀+h·s=<strong>${v}</strong>.`,complexity:6,signature:`${a}:${b}:${t}:${y}:${hn}/${hd}`})}),
T("numericalMethods","trapezoid","Trapezregel",(r,d)=>{const l=r.int(-4,3),w=r.int(1,5),u=l+w,a=nz(r,-5,5),b=r.int(-7,7),fl=a*l+b,fu=a*u+b,v=rat(w*(fl+fu),2);return makeTask({topic:"numericalMethods",id:"numericalMethods.trapezoid",title:"Trapezregel",difficulty:d,prompt:context(`f(x)=${a}x${sign(b)} auf [${l},${u}]`).concat(math("Ein Trapez: Näherungswert?")),answer:{type:"number",value:v},explanation:`T=${w}·(${fl}+${fu})/2=<strong>${v}</strong>.`,complexity:5,signature:`${a}:${b}:${l}:${u}`})}),
T("numericalMethods","rectangle","Rechteckregel",(r,d)=>{const l=r.int(-4,3),w=r.int(1,5),a=nz(r,-5,5),b=r.int(-7,7),mid=new Rational(2*l+w,2),height=new Rational(a).mul(mid).add(b),v=height.mul(w);return makeTask({topic:"numericalMethods",id:"numericalMethods.rectangle",title:"Rechteckregel",difficulty:d,prompt:context(`f(x)=${a}x${sign(b)} auf [${l},${l+w}], Mittelpunktregel`).concat(math("Näherungswert?")),answer:{type:"number",value:v.toString()},explanation:`Mittelpunkt ${mid}, Höhe ${height}, Breite ${w}; Produkt <strong>${v}</strong>.`,complexity:5,signature:`${a}:${b}:${l}:${w}`})})];

export const differentialEquations=[
T("differentialEquations","initial","Anfangswert",(r,d)=>{const a=nz(r,-6,6),C=nz(r,-12,12);return makeTask({topic:"differentialEquations",id:"differentialEquations.initial",title:"Anfangswert",difficulty:d,prompt:context(`y′=${a}y, y(0)=${C}; y=C·e^(${a}t)`).concat(math("Bestimme C.")),input:numberInput("C"),answer:{type:"number",value:C},explanation:`Bei t=0 ist e⁰=1, also <strong>C=${C}</strong>.`,complexity:2,signature:`${a}:${C}`})}),
T("differentialEquations","equilibrium","Stationäre Lösung",(r,d)=>{const a=nz(r,-8,8),y=r.int(-10,10),b=-a*y;return makeTask({topic:"differentialEquations",id:"differentialEquations.equilibrium",title:"Stationäre Lösung",difficulty:d,prompt:context("Bestimme y*.")+math(`y′=${a}y${sign(b)}`),input:numberInput("y*"),answer:{type:"number",value:y},explanation:`0=${a}y*${sign(b)}, daher <strong>y*=${y}</strong>.`,complexity:4,signature:`${a}:${b}`})}),
T("differentialEquations","verify","Lösung überprüfen",(r,d)=>{const a=nz(r,-6,6),c=nz(r,-8,8),shown=r.bool()?a:a+nz(r,-3,3),v=shown===a?"yes":"no",opts=choices(r,v,[v==="yes"?"no":"yes"],x=>x==="yes"?"Ja":"Nein");return makeTask({topic:"differentialEquations",id:"differentialEquations.verify",title:"Lösung überprüfen",difficulty:d,prompt:context(`y′=${a}y`).concat(math(`Ist y=${c}e<sup>${shown}t</sup> eine Lösung?`)),input:choiceInput(opts),answer:{type:"choice",value:v},explanation:`Ableiten liefert y′=${shown}y: <strong>${v==="yes"?"Ja":"Nein"}</strong>.`,complexity:3,signature:`${a}:${c}:${shown}`})}),
T("differentialEquations","characteristic","Charakteristische Gleichung",(r,d)=>{let x=r.int(-8,8),y=r.int(-8,8);if(x===y)y+=1;const p=-(x+y),q=x*y;return makeTask({topic:"differentialEquations",id:"differentialEquations.characteristic",title:"Charakteristische Gleichung",difficulty:d,prompt:context("Bestimme beide Nullstellen.")+math(`λ²${sign(p)}λ${sign(q)}=0`),input:setInput("λ₁; λ₂"),answer:{type:"set",values:[x,y]},explanation:`Faktorisieren ergibt <strong>λ=${x} oder ${y}</strong>.`,complexity:5,signature:`${p}:${q}`})})];

export const trueFalse=[
T("trueFalse","computed","Wahr/Falsch: Rechnen",(r,d)=>{const A=m2(r,7),det=A[0][0]*A[1][1]-A[0][1]*A[1][0],claim=r.bool()?det:det+nz(r,-5,5),v=claim===det;return makeTask({topic:"trueFalse",id:"trueFalse.computed",title:"Wahr oder falsch",difficulty:d,prompt:context("Wahr oder falsch?")+math(`Für A=${matrix(A)} gilt det(A)=${claim}.`),input:boolInput(),answer:{type:"boolean",value:String(v)},explanation:`det(A)=${det}. Die Aussage ist <strong>${v?"wahr":"falsch"}</strong>.`,complexity:4,signature:`${A.flat()}:${claim}`})}),
T("trueFalse","concepts","Wahr/Falsch: Begriffe",(r,d)=>{const n=r.int(1,12),items=[{q:"Jede konvergente Folge ist beschränkt.",v:true,e:"Konvergenz hält die Folge nahe am Grenzwert."},{q:"Jede beschränkte Folge konvergiert.",v:false,e:"Gegenbeispiel: (−1)ⁿ."},{q:"Differenzierbarkeit impliziert Stetigkeit.",v:true,e:"Differenzierbarkeit ist stärker."},{q:"Stetigkeit impliziert Differenzierbarkeit.",v:false,e:"Gegenbeispiel: |x| bei 0."},{q:`P${n} hat Dimension ${n+1}.`,v:true,e:"Basis 1,x,…,xⁿ."}],o=r.pick(items);return makeTask({topic:"trueFalse",id:"trueFalse.concepts",title:"Wahr oder falsch",difficulty:d,prompt:context("Wahr oder falsch?")+math(o.q),input:boolInput(),answer:{type:"boolean",value:String(o.v)},explanation:`<strong>${o.v?"Wahr":"Falsch"}.</strong> ${o.e}`,complexity:3,signature:`${items.indexOf(o)}:${n}:${r.int(0,9999)}`})})];

export const matlab=[
T("matlab","elementwise","MATLAB: elementweise",(r,d)=>{const A=m2(r),pos=r.pick([[0,0],[0,1],[1,0],[1,1]]),v=A[pos[0]][pos[1]]**2;return makeTask({topic:"matlab",id:"matlab.elementwise",title:"MATLAB: elementweise",difficulty:d,prompt:context(`A=${matrix(A)}, B=A.*A`).concat(math(`B(${pos[0]+1},${pos[1]+1})=?`)),answer:{type:"number",value:v},explanation:`.* arbeitet elementweise: <strong>${v}</strong>.`,complexity:2,signature:`${A.flat()}:${pos}`})}),
T("matlab","size","MATLAB: size",(r,d)=>{const rows=r.int(1,8),cols=r.int(1,8),dim=r.pick([1,2]),v=String(dim===1?rows:cols),opts=choices(r,v,[String(rows),String(cols),String(rows*cols),"2"]);return makeTask({topic:"matlab",id:"matlab.size",title:"MATLAB: size",difficulty:d,prompt:context(`A ist ${rows}×${cols}.`).concat(math(`size(A,${dim})=?`)),input:choiceInput(opts),answer:{type:"choice",value:v},explanation:`Dimension ${dim} bedeutet ${dim===1?"Zeilen":"Spalten"}: <strong>${v}</strong>.`,complexity:2,signature:`${rows}:${cols}:${dim}:${r.int(0,9999)}`})})];
