import{createRng}from"./random.js";import{canonicalRaw,checkTaskAnswer}from"./checker.js";import{makeTask,numberInput}from"../topics/helpers.js";
import{generators as basics}from"../topics/basics.js";import{generators as algebra}from"../topics/algebra.js";import{generators as complex}from"../topics/complex.js";import{generators as limits}from"../topics/limits.js";import{generators as sequences}from"../topics/sequences.js";import{generators as series}from"../topics/series.js";import{generators as derivatives}from"../topics/derivatives.js";import{generators as taylor}from"../topics/taylor.js";import{generators as integrals}from"../topics/integrals.js";import{generators as matrices}from"../topics/matrices.js";import{generators as linearSystems}from"../topics/linearSystems.js";import{generators as vectorSpaces}from"../topics/vectorSpaces.js";import{generators as orthogonality}from"../topics/orthogonality.js";import{generators as decompositions}from"../topics/decompositions.js";import{generators as numericalMethods}from"../topics/numericalMethods.js";import{generators as differentialEquations}from"../topics/differentialEquations.js";import{generators as trueFalse}from"../topics/trueFalse.js";import{generators as matlab}from"../topics/matlab.js";
export const TOPICS=Object.freeze([{id:"mixed",label:"Gemischt",short:"Gemischt",enabled:true},{id:"basics",label:"Rechengrundlagen",short:"Grundlagen",enabled:true},{id:"algebra",label:"Algebra & Funktionen",short:"Algebra",enabled:true},{id:"complex",label:"Komplexe Zahlen",short:"Komplex",enabled:true},{id:"limits",label:"Grenzwerte",short:"Grenzwerte",enabled:true},{id:"sequences",label:"Folgen",short:"Folgen",enabled:true},{id:"series",label:"Reihen & Potenzreihen",short:"Reihen",enabled:true},{id:"derivatives",label:"Ableitungen",short:"Ableitungen",enabled:true},{id:"taylor",label:"Taylorpolynome",short:"Taylor",enabled:true},{id:"integrals",label:"Integrale",short:"Integrale",enabled:true},{id:"matrices",label:"Matrizen & Determinanten",short:"Matrizen",enabled:true},{id:"linearSystems",label:"Lineare Gleichungssysteme",short:"LGS",enabled:true},{id:"vectorSpaces",label:"Vektorräume, Basis, Rang & Kern",short:"Vektorräume",enabled:true},{id:"orthogonality",label:"Orthogonalität & Approximation",short:"Orthogonalität",enabled:true},{id:"decompositions",label:"Matrixzerlegungen",short:"Zerlegungen",enabled:true},{id:"numericalMethods",label:"Numerische Verfahren",short:"Numerik",enabled:true},{id:"differentialEquations",label:"Differentialgleichungen",short:"DGL",enabled:true},{id:"trueFalse",label:"Wahr oder falsch",short:"Wahr/Falsch",enabled:true},{id:"matlab",label:"MATLAB & Algorithmen (optional)",short:"MATLAB",enabled:false}]);
const map={basics,algebra,complex,limits,sequences,series,derivatives,taylor,integrals,matrices,linearSystems,vectorSpaces,orthogonality,decompositions,numericalMethods,differentialEquations,trueFalse,matlab};export const registry=Object.freeze(Object.values(map).flat());
const weights=[{value:"basics",weight:14},{value:"algebra",weight:9},{value:"complex",weight:6},{value:"limits",weight:6},{value:"sequences",weight:5},{value:"series",weight:6},{value:"derivatives",weight:8},{value:"taylor",weight:8},{value:"integrals",weight:7},{value:"matrices",weight:8},{value:"linearSystems",weight:7},{value:"vectorSpaces",weight:5},{value:"orthogonality",weight:5},{value:"decompositions",weight:3},{value:"numericalMethods",weight:4},{value:"differentialEquations",weight:4},{value:"trueFalse",weight:6}];
export const topicById=id=>TOPICS.find(x=>x.id===id)||TOPICS[0];export const generatorsForTopic=id=>map[id]||[];
export function resolveDifficulty(r,requested){return requested!=="auto"?requested:r.weighted([{value:"locker",weight:45},{value:"hm1",weight:40},{value:"exam",weight:15}])}
export function validateTask(t){if(!t||![t.id,t.topic,t.generatorId,t.difficulty,t.prompt,t.explanation,t.signature].every(x=>typeof x==="string"&&x&&!/undefined|NaN/.test(x)))return false;if(!t.inputSpec||!t.answer||!Number.isFinite(t.complexity)||t.complexity<1||t.estimatedSeconds<5||t.estimatedSeconds>90)return false;const r=checkTaskAnswer(t,canonicalRaw(t));return r.valid&&r.correct}
function fallback(r,d){const a=r.int(-9,9),b=r.int(-9,9);return makeTask({topic:"basics",id:"fallback.add",title:"Ersatzaufgabe",difficulty:d,prompt:`<span class="context">Berechne.</span>${a}+(${b})`,input:numberInput(),answer:{type:"number",value:a+b},explanation:`${a}+(${b})=<strong>${a+b}</strong>.`,complexity:1,signature:`${a}:${b}:${r.int(0,99999)}`})}
export function generateTask({topic="mixed",difficulty="auto",history=[],matlabEnabled=false,seed}={}){const r=createRng(seed),d=resolveDifficulty(r,difficulty),recent=new Set(history.slice(-20));let last=null;for(let i=0;i<80;i++){let chosen=topic;if(chosen==="mixed")chosen=r.weighted(matlabEnabled?[...weights,{value:"matlab",weight:2}]:weights);if(chosen==="matlab"&&!matlabEnabled)chosen="basics";const g=r.pick(map[chosen]||basics);try{const t=g.generate(r,d);if(!validateTask(t))continue;last=t;if(!recent.has(t.signature))return t}catch(e){console.warn(`Generator ${g.id} fehlgeschlagen`,e)}}return last||fallback(r,d)}
