import{checkTaskAnswer}from"./core/checker.js";import{generateTask,TOPICS,topicById}from"./core/registry.js";import{load,save}from"./core/storage.js";import{collect,disable,renderInputs}from"./ui/inputs.js";
const $=s=>document.querySelector(s),el={start:$("#start"),exercise:$("#exercise"),topic:$("#topic"),difficulty:$("#difficulty"),hint:$("#difficulty-hint"),matlab:$("#matlab"),startButton:$("#start-button"),back:$("#back"),meta:$("#meta"),score:$("#score"),time:$("#time"),kind:$("#kind"),prompt:$("#prompt"),form:$("#form"),inputs:$("#inputs"),check:$("#check"),feedback:$("#feedback"),actions:$("#actions"),retry:$("#retry"),solutionButton:$("#solution-button"),next:$("#next"),solution:$("#solution"),solutionText:$("#solution-text"),update:$("#update"),reload:$("#reload")};
const state=load();let task=null,checked=false,counted=false;
function topics(){const current=el.topic.value||state.topic;el.topic.replaceChildren();TOPICS.filter(x=>x.enabled||state.matlab).forEach(x=>{const o=document.createElement("option");o.value=x.id;o.textContent=x.label;el.topic.append(o)});el.topic.value=[...el.topic.options].some(x=>x.value===current)?current:"mixed"}
function persist(){state.topic=el.topic.value;state.difficulty=el.difficulty.value;state.matlab=el.matlab.checked;save(state)}
function score(){el.score.textContent=`${state.score.correct} ✓ · ${state.score.wrong} ✕`;el.score.setAttribute("aria-label",`${state.score.correct} richtig, ${state.score.wrong} falsch`)}
function feedback(type,text){el.feedback.className=`feedback ${type}`;el.feedback.textContent=text;el.feedback.hidden=false}
function next(){persist();task=generateTask({topic:state.topic,difficulty:state.difficulty,history:state.recent,matlabEnabled:state.matlab});state.recent.push(task.signature);state.recent=state.recent.slice(-20);checked=false;counted=false;el.meta.textContent=`${topicById(task.topic).short} · ${{locker:"Locker",hm1:"HM1-Baustein",exam:"Klausurnah"}[task.difficulty]}`;el.time.textContent=`${task.estimatedSeconds} s`;el.kind.textContent=task.title;el.prompt.innerHTML=task.prompt;el.solutionText.innerHTML=task.explanation;el.feedback.hidden=true;el.actions.hidden=true;el.solution.hidden=true;el.check.hidden=false;const first=renderInputs(el.inputs,task.inputSpec);requestAnimationFrame(()=>first?.focus({preventScroll:true}));save(state)}
function submit(e){e.preventDefault();if(checked){next();return}const result=checkTaskAnswer(task,collect(el.inputs,task.inputSpec));if(!result.valid){feedback("neutral",result.message);return}checked=true;if(!counted){state.score[result.correct?"correct":"wrong"]++;counted=true}score();save(state);feedback(result.correct?"ok":"bad",result.correct?"Richtig! Stark.":"Noch nicht richtig.");el.actions.hidden=false;el.retry.hidden=result.correct;el.solutionButton.hidden=false;el.check.hidden=true;disable(el.inputs,result.correct);if(result.correct)el.next.focus()}
function retry(){checked=false;el.feedback.hidden=true;el.actions.hidden=true;el.solution.hidden=true;el.check.hidden=false;disable(el.inputs,false);el.inputs.querySelector("input")?.focus()}
function hints(){el.hint.textContent={auto:"45 % locker · 40 % HM1 · 15 % klausurnah",locker:"Kleine Zahlen und meist ein Schritt.",hm1:"Kurze typische HM1-Rechenbausteine.",exam:"Klausurkonzepte mit einfachen Zahlen."}[el.difficulty.value]}
el.difficulty.value=state.difficulty;el.matlab.checked=state.matlab;topics();el.topic.value=state.topic||"mixed";hints();score();el.startButton.addEventListener("click",()=>{el.start.hidden=true;el.exercise.hidden=false;next()});el.back.addEventListener("click",()=>{el.exercise.hidden=true;el.start.hidden=false;el.startButton.focus()});el.form.addEventListener("submit",submit);el.retry.addEventListener("click",retry);el.solutionButton.addEventListener("click",()=>{el.solution.hidden=false;el.solutionButton.hidden=true;el.solution.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion:reduce)").matches?"auto":"smooth",block:"nearest"})});el.next.addEventListener("click",next);el.topic.addEventListener("change",persist);el.difficulty.addEventListener("change",()=>{hints();persist()});el.matlab.addEventListener("change",()=>{state.matlab=el.matlab.checked;topics();persist()});
if("serviceWorker"in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("./sw.js").then(reg=>{if(reg.waiting)el.update.hidden=false;reg.addEventListener("updatefound",()=>reg.installing?.addEventListener("statechange",()=>{if(reg.installing?.state==="installed"&&navigator.serviceWorker.controller)el.update.hidden=false}));el.reload.addEventListener("click",()=>{reg.waiting?.postMessage({type:"SKIP_WAITING"});location.reload()})}).catch(e=>console.info("Offline-Modus nicht registriert",e));
